Repository mash-up-kr/study-android-architecture, pull requests merged in 2019-10, with the labels that each got.

#8 Dlwls5201
  dlwls5201/README.md
Labels: documentation

#16 프로젝트 처음 커밋입니다.
  namget/.gitignore
  namget/.idea/codeStyles/Project.xml
  namget/.idea/codeStyles/codeStyleConfig.xml
  namget/.idea/runConfigurations.xml
  namget/app/.gitignore
  namget/app/build.gradle
  namget/app/proguard-rules.pro
  namget/app/src/androidTest/java/com/namget/myarchitecture/ExampleInstrumentedTest.kt
  namget/app/src/main/AndroidManifest.xml
  namget/app/src/main/java/com/namget/myarchitecture/MainActivity.kt
  namget/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  namget/app/src/main/res/drawable/ic_launcher_background.xml
  namget/app/src/main/res/layout/activity_main.xml
  namget/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  namget/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  namget/app/src/main/res/mipmap-hdpi/ic_launcher.png
  namget/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  namget/app/src/main/res/mipmap-mdpi/ic_launcher.png
  namget/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  namget/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  namget/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  namget/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  namget/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  namget/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  namget/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  namget/app/src/main/res/values/colors.xml
  namget/app/src/main/res/values/strings.xml
  namget/app/src/main/res/values/styles.xml
  namget/app/src/test/java/com/namget/myarchitecture/ExampleUnitTest.kt
  namget/build.gradle
  namget/gradle.properties
  namget/gradle/wrapper/gradle-wrapper.jar
  namget/gradle/wrapper/gradle-wrapper.properties
  namget/gradlew
  namget/gradlew.bat
  namget/settings.gradle
Labels: Merge Needed

#17 과제 1
  myung6024/MyToyProject/.gitignore
  myung6024/MyToyProject/.idea/codeStyles/Project.xml
  myung6024/MyToyProject/.idea/codeStyles/codeStyleConfig.xml
  myung6024/MyToyProject/app/.gitignore
  myung6024/MyToyProject/app/build.gradle
  myung6024/MyToyProject/app/proguard-rules.pro
  myung6024/MyToyProject/app/src/androidTest/java/com/runeanim/mytoyproject/ExampleInstrumentedTest.kt
  myung6024/MyToyProject/app/src/main/AndroidManifest.xml
  myung6024/MyToyProject/app/src/main/java/com/runeanim/mytoyproject/MainActivity.kt
  myung6024/MyToyProject/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  myung6024/MyToyProject/app/src/main/res/drawable/ic_launcher_background.xml
  myung6024/MyToyProject/app/src/main/res/layout/activity_main.xml
  myung6024/MyToyProject/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  myung6024/MyToyProject/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  myung6024/MyToyProject/app/src/main/res/mipmap-hdpi/ic_launcher.png
  myung6024/MyToyProject/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  myung6024/MyToyProject/app/src/main/res/mipmap-mdpi/ic_launcher.png
  myung6024/MyToyProject/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  myung6024/MyToyProject/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  myung6024/MyToyProject/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  myung6024/MyToyProject/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  myung6024/MyToyProject/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  myung6024/MyToyProject/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  myung6024/MyToyProject/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  myung6024/MyToyProject/app/src/main/res/values/colors.xml
  myung6024/MyToyProject/app/src/main/res/values/strings.xml
  myung6024/MyToyProject/app/src/main/res/values/styles.xml
  myung6024/MyToyProject/app/src/test/java/com/runeanim/mytoyproject/ExampleUnitTest.kt
  myung6024/MyToyProject/build.gradle
  myung6024/MyToyProject/gradle.properties
  myung6024/MyToyProject/gradle/wrapper/gradle-wrapper.jar
  myung6024/MyToyProject/gradle/wrapper/gradle-wrapper.properties
  myung6024/MyToyProject/gradlew
  myung6024/MyToyProject/gradlew.bat
  myung6024/MyToyProject/settings.gradle
Labels: Merge Needed

#18 HW-1 프로젝트 생성 및 gitIgnore 추가
  preludezdev/.gitignore
  preludezdev/.idea/codeStyles/Project.xml
  preludezdev/.idea/runConfigurations.xml
  preludezdev/app/.gitignore
  preludezdev/app/build.gradle
  preludezdev/app/proguard-rules.pro
  preludezdev/app/src/androidTest/java/com/example/mashuparchitecture/ExampleInstrumentedTest.kt
  preludezdev/app/src/main/AndroidManifest.xml
  preludezdev/app/src/main/java/com/example/mashuparchitecture/MainActivity.kt
  preludezdev/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  preludezdev/app/src/main/res/drawable/ic_launcher_background.xml
  preludezdev/app/src/main/res/layout/activity_main.xml
  preludezdev/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  preludezdev/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  preludezdev/app/src/main/res/mipmap-hdpi/ic_launcher.png
  preludezdev/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  preludezdev/app/src/main/res/mipmap-mdpi/ic_launcher.png
  preludezdev/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  preludezdev/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  preludezdev/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  preludezdev/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  preludezdev/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  preludezdev/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  preludezdev/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  preludezdev/app/src/main/res/values/colors.xml
  preludezdev/app/src/main/res/values/strings.xml
  preludezdev/app/src/main/res/values/styles.xml
  preludezdev/app/src/test/java/com/example/mashuparchitecture/ExampleUnitTest.kt
  preludezdev/build.gradle
  preludezdev/gradle.properties
  preludezdev/gradle/wrapper/gradle-wrapper.jar
  preludezdev/gradle/wrapper/gradle-wrapper.properties
  preludezdev/gradlew
  preludezdev/gradlew.bat
  preludezdev/settings.gradle
Labels: Merge Needed

#14 과제1 작업
  dlwls5201/MashUpArchitecture/.gitignore
  dlwls5201/MashUpArchitecture/.idea/codeStyles/Project.xml
  dlwls5201/MashUpArchitecture/.idea/codeStyles/codeStyleConfig.xml
  dlwls5201/MashUpArchitecture/.idea/runConfigurations.xml
  dlwls5201/MashUpArchitecture/app/.gitignore
  dlwls5201/MashUpArchitecture/app/build.gradle
  dlwls5201/MashUpArchitecture/app/proguard-rules.pro
  dlwls5201/MashUpArchitecture/app/src/androidTest/java/com/tistory/mashuparchitecture/ExampleInstrumentedTest.kt
  dlwls5201/MashUpArchitecture/app/src/main/AndroidManifest.xml
  dlwls5201/MashUpArchitecture/app/src/main/java/com/tistory/mashuparchitecture/MainActivity.kt
  dlwls5201/MashUpArchitecture/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  dlwls5201/MashUpArchitecture/app/src/main/res/drawable/ic_launcher_background.xml
  dlwls5201/MashUpArchitecture/app/src/main/res/layout/activity_main.xml
  dlwls5201/MashUpArchitecture/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  dlwls5201/MashUpArchitecture/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  dlwls5201/MashUpArchitecture/app/src/main/res/mipmap-hdpi/ic_launcher.png
  dlwls5201/MashUpArchitecture/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  dlwls5201/MashUpArchitecture/app/src/main/res/mipmap-mdpi/ic_launcher.png
  dlwls5201/MashUpArchitecture/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  dlwls5201/MashUpArchitecture/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  dlwls5201/MashUpArchitecture/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  dlwls5201/MashUpArchitecture/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  dlwls5201/MashUpArchitecture/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  dlwls5201/MashUpArchitecture/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  dlwls5201/MashUpArchitecture/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  dlwls5201/MashUpArchitecture/app/src/main/res/values/colors.xml
  dlwls5201/MashUpArchitecture/app/src/main/res/values/strings.xml
  dlwls5201/MashUpArchitecture/app/src/main/res/values/styles.xml
  dlwls5201/MashUpArchitecture/app/src/test/java/com/tistory/mashuparchitecture/ExampleUnitTest.kt
  dlwls5201/MashUpArchitecture/build.gradle
  dlwls5201/MashUpArchitecture/gradle.properties
  dlwls5201/MashUpArchitecture/gradle/wrapper/gradle-wrapper.jar
  dlwls5201/MashUpArchitecture/gradle/wrapper/gradle-wrapper.properties
  dlwls5201/MashUpArchitecture/gradlew
  dlwls5201/MashUpArchitecture/gradlew.bat
  dlwls5201/MashUpArchitecture/settings.gradle
Labels: Review Needed

#22 make file
  miinjung/.idea/workspace.xml
  miinjung/test/.gitignore
  miinjung/test/.idea/codeStyles/Project.xml
  miinjung/test/.idea/codeStyles/codeStyleConfig.xml
  miinjung/test/.idea/runConfigurations.xml
  miinjung/test/app/.gitignore
  miinjung/test/app/build.gradle
  miinjung/test/app/proguard-rules.pro
  miinjung/test/app/src/androidTest/java/miinjung/study/test/ExampleInstrumentedTest.kt
  miinjung/test/app/src/main/AndroidManifest.xml
  miinjung/test/app/src/main/java/miinjung/study/test/MainActivity.kt
  miinjung/test/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  miinjung/test/app/src/main/res/drawable/ic_launcher_background.xml
  miinjung/test/app/src/main/res/layout/activity_main.xml
  miinjung/test/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  miinjung/test/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  miinjung/test/app/src/main/res/mipmap-hdpi/ic_launcher.png
  miinjung/test/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  miinjung/test/app/src/main/res/mipmap-mdpi/ic_launcher.png
  miinjung/test/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  miinjung/test/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  miinjung/test/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  miinjung/test/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  miinjung/test/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  miinjung/test/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  miinjung/test/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  miinjung/test/app/src/main/res/values/colors.xml
  miinjung/test/app/src/main/res/values/strings.xml
  miinjung/test/app/src/main/res/values/styles.xml
  miinjung/test/app/src/test/java/miinjung/study/test/ExampleUnitTest.kt
  miinjung/test/build.gradle
  miinjung/test/gradle.properties
  miinjung/test/gradle/wrapper/gradle-wrapper.jar
  miinjung/test/gradle/wrapper/gradle-wrapper.properties
  miinjung/test/gradlew
  miinjung/test/gradlew.bat
  miinjung/test/settings.gradle
Labels: Merge Needed
